apiVersion: v1
kind: Service
metadata:
  name: {{ include "abiemarket-auth-service.name" . }}-service
  labels: {{ include "abiemarket-auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "abiemarket-auth-service.selectorLabels" . | nindent 4 }}
